language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update -qq

install:
  - >
    sudo apt-get install -qq
    cppcheck
    libboost-program-options-dev libboost-system-dev
    libpcp3 libpcp3-dev libpcp-pmda3 libpcp-pmda3-dev
    libqmfconsole2-dev libqpidclient2-dev libqpidcommon2-dev libqpidtypes1-dev
    pcp
  - PCP_PMDA_CPP_VERSION=v0.4.0
  - wget --content-disposition --directory-prefix /tmp
    https://github.com/pcolby/pcp-pmda-cpp/archive/$PCP_PMDA_CPP_VERSION.tar.gz
  - tar xvzf /tmp/pcp-pmda-cpp-`echo $PCP_PMDA_CPP_VERSION | sed 's/^v//'`.tar.gz -C /tmp
  - pushd /tmp/pcp-pmda-cpp-`echo $PCP_PMDA_CPP_VERSION | sed 's/^v//'`/include
  - cmake . && sudo make install
  - popd

before_script:
  - mkdir -p build

script:
  - cppcheck --error-exitcode=1 --quiet .
  - pushd build
  - cmake .. && make && sudo make install
  - popd
