language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update -qq

install:
  - >
    sudo apt-get install -qq
    libboost-program-options-dev
    libpcp3 libpcp3-dev libpcp-pmda3 libpcp-pmda3-dev
    libqmfconsole2-dev libqpidclient2-dev libqpidcommon2-dev libqpidtypes1-dev
  - wget -P /tmp https://github.com/pcolby/pcp-pmda-cpp/archive/master.zip
  - unzip -d /tmp /tmp/master.zip
  - pushd /tmp/pcp-pmda-cpp-master/include
  - cmake . && sudo make install
  - popd

before_script:
  - mkdir -p build

script:
  - pushd build
  - cmake .. && make
  - popd
